package com.youssef.gamal.ecommerce.microservice.product.query.entities;

import java.io.Serializable;
import java.time.LocalDateTime;

import org.springframework.data.annotation.Id;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@SuppressWarnings("serial")
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class CategoryView implements Serializable {

	@Id
    private String snapshotId; // generated by mongoDB

    private String originalId; // snapshotId of the category in the command service

    private String name;

    private LocalDateTime creationDate;

    private String createdBy;

    private LocalDateTime lastModifiedDate;

    private String lastModifiedBy;

    private String eventType;
}
