package com.youssef.gamal.ecommerce.microservice.product.query.entities;


import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.io.Serializable;
import java.time.LocalDateTime;

@Document(collection = "products")
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class ProductView implements Serializable {

    @Id
    private String id; // generated by mongoDB

    private String originalId; // id of the product in the command service

    private String name;

    private String description;

    private double price;

    private int quantity;

    private LocalDateTime creationDate;

    private String createdBy;

    private LocalDateTime lastModifiedDate;

    private String lastModifiedBy;

    private String eventType;

}
