package com.youssef.gamal.ecommerce.microservice.product.query.entities;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Set;
import java.util.UUID;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@SuppressWarnings("serial")
@Document(collection = "products")
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class ProductView implements Serializable {

    @Id
    @Builder.Default
    private String snapshotId = UUID.randomUUID().toString(); // generated by application

    private String originalId; // snapshotId of the product in the command service

    private String name;

    private String description;

    @Indexed
    private Set<CategoryView> categories;

    private double price;

    private int quantity;

    private LocalDateTime creationDate;

    private String createdBy;

    private LocalDateTime lastModifiedDate;

    private String lastModifiedBy;

    private String eventType;
}
