# Spring Boot Application Configuration
spring:
  application:
    name: product-query-service
  # MongoDB Configuration
  data:
    mongodb:
      uri: mongodb://adminProductsQueryDB:Password123@localhost:27017/productQueryDb?authSource=admin
      host: localhost
      port: 27017
      database: productQueryDb
      username: adminProductsQueryDB
      password: Password123
    # Redis Configuration
    redis:
      host: localhost
      port: 6379

  # Kafka Configuration
  kafka:
    consumer:
      group-id: "product-query-consumer-group"
      keyDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      valueDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      properties:
        schema:
          registry:
            url: "http://127.0.0.1:8081"
        specific:
          avro:
            reader: "true"

  # Redis Cache Configuration
  cache:
    type: redis


# Event Driven Topics/Queue
kafka:
  event-names:
    product-event: products-event
    
# Server Configuration
server:
  port: 8082
  servlet:
    context-path: /ecommerce/api/v1

# Logging Configuration
logging:
  level:
    org:
      springframework:
        cache: TRACE

