version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-products-command
    environment:
      POSTGRES_DB: products-command-db
      POSTGRES_USER: admin-products-command-db
      POSTGRES_PASSWORD: P@ssw0rd@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: mongo-products-query
    environment:
      MONGO_INITDB_DATABASE: productQueryDb
      MONGO_INITDB_ROOT_USERNAME: adminProductsQueryDB
      MONGO_INITDB_ROOT_PASSWORD: Password123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data:
