/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CategoryRef extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5263079209366584805L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CategoryRef\",\"namespace\":\"com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events\",\"fields\":[{\"name\":\"snapshotId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"originalId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CategoryRef> ENCODER =
      new BinaryMessageEncoder<CategoryRef>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CategoryRef> DECODER =
      new BinaryMessageDecoder<CategoryRef>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CategoryRef> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CategoryRef> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CategoryRef> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CategoryRef>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CategoryRef to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CategoryRef from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CategoryRef instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CategoryRef fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String snapshotId;
  private java.lang.String originalId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CategoryRef() {}

  /**
   * All-args constructor.
   * @param snapshotId The new value for snapshotId
   * @param originalId The new value for originalId
   */
  public CategoryRef(java.lang.String snapshotId, java.lang.String originalId) {
    this.snapshotId = snapshotId;
    this.originalId = originalId;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return snapshotId;
    case 1: return originalId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: snapshotId = value$ != null ? value$.toString() : null; break;
    case 1: originalId = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'snapshotId' field.
   * @return The value of the 'snapshotId' field.
   */
  public java.lang.String getSnapshotId() {
    return snapshotId;
  }


  /**
   * Sets the value of the 'snapshotId' field.
   * @param value the value to set.
   */
  public void setSnapshotId(java.lang.String value) {
    this.snapshotId = value;
  }

  /**
   * Gets the value of the 'originalId' field.
   * @return The value of the 'originalId' field.
   */
  public java.lang.String getOriginalId() {
    return originalId;
  }


  /**
   * Sets the value of the 'originalId' field.
   * @param value the value to set.
   */
  public void setOriginalId(java.lang.String value) {
    this.originalId = value;
  }

  /**
   * Creates a new CategoryRef RecordBuilder.
   * @return A new CategoryRef RecordBuilder
   */
  public static com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef.Builder newBuilder() {
    return new com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef.Builder();
  }

  /**
   * Creates a new CategoryRef RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CategoryRef RecordBuilder
   */
  public static com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef.Builder newBuilder(com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef.Builder other) {
    if (other == null) {
      return new com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef.Builder();
    } else {
      return new com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef.Builder(other);
    }
  }

  /**
   * Creates a new CategoryRef RecordBuilder by copying an existing CategoryRef instance.
   * @param other The existing instance to copy.
   * @return A new CategoryRef RecordBuilder
   */
  public static com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef.Builder newBuilder(com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef other) {
    if (other == null) {
      return new com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef.Builder();
    } else {
      return new com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef.Builder(other);
    }
  }

  /**
   * RecordBuilder for CategoryRef instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CategoryRef>
    implements org.apache.avro.data.RecordBuilder<CategoryRef> {

    private java.lang.String snapshotId;
    private java.lang.String originalId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.snapshotId)) {
        this.snapshotId = data().deepCopy(fields()[0].schema(), other.snapshotId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.originalId)) {
        this.originalId = data().deepCopy(fields()[1].schema(), other.originalId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing CategoryRef instance
     * @param other The existing instance to copy.
     */
    private Builder(com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.snapshotId)) {
        this.snapshotId = data().deepCopy(fields()[0].schema(), other.snapshotId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.originalId)) {
        this.originalId = data().deepCopy(fields()[1].schema(), other.originalId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'snapshotId' field.
      * @return The value.
      */
    public java.lang.String getSnapshotId() {
      return snapshotId;
    }


    /**
      * Sets the value of the 'snapshotId' field.
      * @param value The value of 'snapshotId'.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef.Builder setSnapshotId(java.lang.String value) {
      validate(fields()[0], value);
      this.snapshotId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'snapshotId' field has been set.
      * @return True if the 'snapshotId' field has been set, false otherwise.
      */
    public boolean hasSnapshotId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'snapshotId' field.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef.Builder clearSnapshotId() {
      snapshotId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'originalId' field.
      * @return The value.
      */
    public java.lang.String getOriginalId() {
      return originalId;
    }


    /**
      * Sets the value of the 'originalId' field.
      * @param value The value of 'originalId'.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef.Builder setOriginalId(java.lang.String value) {
      validate(fields()[1], value);
      this.originalId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'originalId' field has been set.
      * @return True if the 'originalId' field has been set, false otherwise.
      */
    public boolean hasOriginalId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'originalId' field.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef.Builder clearOriginalId() {
      originalId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CategoryRef build() {
      try {
        CategoryRef record = new CategoryRef();
        record.snapshotId = fieldSetFlags()[0] ? this.snapshotId : (java.lang.String) defaultValue(fields()[0]);
        record.originalId = fieldSetFlags()[1] ? this.originalId : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CategoryRef>
    WRITER$ = (org.apache.avro.io.DatumWriter<CategoryRef>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CategoryRef>
    READER$ = (org.apache.avro.io.DatumReader<CategoryRef>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.snapshotId);

    out.writeString(this.originalId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.snapshotId = in.readString();

      this.originalId = in.readString();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.snapshotId = in.readString();
          break;

        case 1:
          this.originalId = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










