/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ProductEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5079441052563027254L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProductEvent\",\"namespace\":\"com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events\",\"fields\":[{\"name\":\"originalId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"snapshotId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"eventType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"description\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"price\",\"type\":\"double\"},{\"name\":\"quantity\",\"type\":\"int\"},{\"name\":\"creationDate\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}],\"default\":null},{\"name\":\"createdBy\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"lastModifiedDate\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}],\"default\":null},{\"name\":\"lastModifiedBy\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"categoryIds\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}],\"default\":null},{\"name\":\"categories\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"CategoryRef\",\"fields\":[{\"name\":\"snapshotId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"originalId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<ProductEvent> ENCODER =
      new BinaryMessageEncoder<ProductEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProductEvent> DECODER =
      new BinaryMessageDecoder<ProductEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProductEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProductEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProductEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ProductEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProductEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProductEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProductEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProductEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String originalId;
  private java.lang.String snapshotId;
  private java.lang.String eventType;
  private java.lang.String name;
  private java.lang.String description;
  private double price;
  private int quantity;
  private java.time.Instant creationDate;
  private java.lang.String createdBy;
  private java.time.Instant lastModifiedDate;
  private java.lang.String lastModifiedBy;
  private long timestamp;
  private java.util.List<java.lang.String> categoryIds;
  private java.util.List<com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef> categories;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProductEvent() {}

  /**
   * All-args constructor.
   * @param originalId The new value for originalId
   * @param snapshotId The new value for snapshotId
   * @param eventType The new value for eventType
   * @param name The new value for name
   * @param description The new value for description
   * @param price The new value for price
   * @param quantity The new value for quantity
   * @param creationDate The new value for creationDate
   * @param createdBy The new value for createdBy
   * @param lastModifiedDate The new value for lastModifiedDate
   * @param lastModifiedBy The new value for lastModifiedBy
   * @param timestamp The new value for timestamp
   * @param categoryIds The new value for categoryIds
   * @param categories The new value for categories
   */
  public ProductEvent(java.lang.String originalId, java.lang.String snapshotId, java.lang.String eventType, java.lang.String name, java.lang.String description, java.lang.Double price, java.lang.Integer quantity, java.time.Instant creationDate, java.lang.String createdBy, java.time.Instant lastModifiedDate, java.lang.String lastModifiedBy, java.lang.Long timestamp, java.util.List<java.lang.String> categoryIds, java.util.List<com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef> categories) {
    this.originalId = originalId;
    this.snapshotId = snapshotId;
    this.eventType = eventType;
    this.name = name;
    this.description = description;
    this.price = price;
    this.quantity = quantity;
    this.creationDate = creationDate;
    this.createdBy = createdBy;
    this.lastModifiedDate = lastModifiedDate;
    this.lastModifiedBy = lastModifiedBy;
    this.timestamp = timestamp;
    this.categoryIds = categoryIds;
    this.categories = categories;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return originalId;
    case 1: return snapshotId;
    case 2: return eventType;
    case 3: return name;
    case 4: return description;
    case 5: return price;
    case 6: return quantity;
    case 7: return creationDate;
    case 8: return createdBy;
    case 9: return lastModifiedDate;
    case 10: return lastModifiedBy;
    case 11: return timestamp;
    case 12: return categoryIds;
    case 13: return categories;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: originalId = value$ != null ? value$.toString() : null; break;
    case 1: snapshotId = value$ != null ? value$.toString() : null; break;
    case 2: eventType = value$ != null ? value$.toString() : null; break;
    case 3: name = value$ != null ? value$.toString() : null; break;
    case 4: description = value$ != null ? value$.toString() : null; break;
    case 5: price = (java.lang.Double)value$; break;
    case 6: quantity = (java.lang.Integer)value$; break;
    case 7: creationDate = (java.time.Instant)value$; break;
    case 8: createdBy = value$ != null ? value$.toString() : null; break;
    case 9: lastModifiedDate = (java.time.Instant)value$; break;
    case 10: lastModifiedBy = value$ != null ? value$.toString() : null; break;
    case 11: timestamp = (java.lang.Long)value$; break;
    case 12: categoryIds = (java.util.List<java.lang.String>)value$; break;
    case 13: categories = (java.util.List<com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'originalId' field.
   * @return The value of the 'originalId' field.
   */
  public java.lang.String getOriginalId() {
    return originalId;
  }


  /**
   * Sets the value of the 'originalId' field.
   * @param value the value to set.
   */
  public void setOriginalId(java.lang.String value) {
    this.originalId = value;
  }

  /**
   * Gets the value of the 'snapshotId' field.
   * @return The value of the 'snapshotId' field.
   */
  public java.lang.String getSnapshotId() {
    return snapshotId;
  }


  /**
   * Sets the value of the 'snapshotId' field.
   * @param value the value to set.
   */
  public void setSnapshotId(java.lang.String value) {
    this.snapshotId = value;
  }

  /**
   * Gets the value of the 'eventType' field.
   * @return The value of the 'eventType' field.
   */
  public java.lang.String getEventType() {
    return eventType;
  }


  /**
   * Sets the value of the 'eventType' field.
   * @param value the value to set.
   */
  public void setEventType(java.lang.String value) {
    this.eventType = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.String getDescription() {
    return description;
  }


  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.String value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'price' field.
   * @return The value of the 'price' field.
   */
  public double getPrice() {
    return price;
  }


  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(double value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'quantity' field.
   * @return The value of the 'quantity' field.
   */
  public int getQuantity() {
    return quantity;
  }


  /**
   * Sets the value of the 'quantity' field.
   * @param value the value to set.
   */
  public void setQuantity(int value) {
    this.quantity = value;
  }

  /**
   * Gets the value of the 'creationDate' field.
   * @return The value of the 'creationDate' field.
   */
  public java.time.Instant getCreationDate() {
    return creationDate;
  }


  /**
   * Sets the value of the 'creationDate' field.
   * @param value the value to set.
   */
  public void setCreationDate(java.time.Instant value) {
    this.creationDate = value;
  }

  /**
   * Gets the value of the 'createdBy' field.
   * @return The value of the 'createdBy' field.
   */
  public java.lang.String getCreatedBy() {
    return createdBy;
  }


  /**
   * Sets the value of the 'createdBy' field.
   * @param value the value to set.
   */
  public void setCreatedBy(java.lang.String value) {
    this.createdBy = value;
  }

  /**
   * Gets the value of the 'lastModifiedDate' field.
   * @return The value of the 'lastModifiedDate' field.
   */
  public java.time.Instant getLastModifiedDate() {
    return lastModifiedDate;
  }


  /**
   * Sets the value of the 'lastModifiedDate' field.
   * @param value the value to set.
   */
  public void setLastModifiedDate(java.time.Instant value) {
    this.lastModifiedDate = value;
  }

  /**
   * Gets the value of the 'lastModifiedBy' field.
   * @return The value of the 'lastModifiedBy' field.
   */
  public java.lang.String getLastModifiedBy() {
    return lastModifiedBy;
  }


  /**
   * Sets the value of the 'lastModifiedBy' field.
   * @param value the value to set.
   */
  public void setLastModifiedBy(java.lang.String value) {
    this.lastModifiedBy = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'categoryIds' field.
   * @return The value of the 'categoryIds' field.
   */
  public java.util.List<java.lang.String> getCategoryIds() {
    return categoryIds;
  }


  /**
   * Sets the value of the 'categoryIds' field.
   * @param value the value to set.
   */
  public void setCategoryIds(java.util.List<java.lang.String> value) {
    this.categoryIds = value;
  }

  /**
   * Gets the value of the 'categories' field.
   * @return The value of the 'categories' field.
   */
  public java.util.List<com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef> getCategories() {
    return categories;
  }


  /**
   * Sets the value of the 'categories' field.
   * @param value the value to set.
   */
  public void setCategories(java.util.List<com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef> value) {
    this.categories = value;
  }

  /**
   * Creates a new ProductEvent RecordBuilder.
   * @return A new ProductEvent RecordBuilder
   */
  public static com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder newBuilder() {
    return new com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder();
  }

  /**
   * Creates a new ProductEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProductEvent RecordBuilder
   */
  public static com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder newBuilder(com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder other) {
    if (other == null) {
      return new com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder();
    } else {
      return new com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder(other);
    }
  }

  /**
   * Creates a new ProductEvent RecordBuilder by copying an existing ProductEvent instance.
   * @param other The existing instance to copy.
   * @return A new ProductEvent RecordBuilder
   */
  public static com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder newBuilder(com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent other) {
    if (other == null) {
      return new com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder();
    } else {
      return new com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProductEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProductEvent>
    implements org.apache.avro.data.RecordBuilder<ProductEvent> {

    private java.lang.String originalId;
    private java.lang.String snapshotId;
    private java.lang.String eventType;
    private java.lang.String name;
    private java.lang.String description;
    private double price;
    private int quantity;
    private java.time.Instant creationDate;
    private java.lang.String createdBy;
    private java.time.Instant lastModifiedDate;
    private java.lang.String lastModifiedBy;
    private long timestamp;
    private java.util.List<java.lang.String> categoryIds;
    private java.util.List<com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef> categories;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.originalId)) {
        this.originalId = data().deepCopy(fields()[0].schema(), other.originalId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.snapshotId)) {
        this.snapshotId = data().deepCopy(fields()[1].schema(), other.snapshotId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.eventType)) {
        this.eventType = data().deepCopy(fields()[2].schema(), other.eventType);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.name)) {
        this.name = data().deepCopy(fields()[3].schema(), other.name);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.description)) {
        this.description = data().deepCopy(fields()[4].schema(), other.description);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.price)) {
        this.price = data().deepCopy(fields()[5].schema(), other.price);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.quantity)) {
        this.quantity = data().deepCopy(fields()[6].schema(), other.quantity);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.creationDate)) {
        this.creationDate = data().deepCopy(fields()[7].schema(), other.creationDate);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.createdBy)) {
        this.createdBy = data().deepCopy(fields()[8].schema(), other.createdBy);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.lastModifiedDate)) {
        this.lastModifiedDate = data().deepCopy(fields()[9].schema(), other.lastModifiedDate);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.lastModifiedBy)) {
        this.lastModifiedBy = data().deepCopy(fields()[10].schema(), other.lastModifiedBy);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[11].schema(), other.timestamp);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.categoryIds)) {
        this.categoryIds = data().deepCopy(fields()[12].schema(), other.categoryIds);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.categories)) {
        this.categories = data().deepCopy(fields()[13].schema(), other.categories);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
    }

    /**
     * Creates a Builder by copying an existing ProductEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.originalId)) {
        this.originalId = data().deepCopy(fields()[0].schema(), other.originalId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.snapshotId)) {
        this.snapshotId = data().deepCopy(fields()[1].schema(), other.snapshotId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.eventType)) {
        this.eventType = data().deepCopy(fields()[2].schema(), other.eventType);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.name)) {
        this.name = data().deepCopy(fields()[3].schema(), other.name);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.description)) {
        this.description = data().deepCopy(fields()[4].schema(), other.description);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.price)) {
        this.price = data().deepCopy(fields()[5].schema(), other.price);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.quantity)) {
        this.quantity = data().deepCopy(fields()[6].schema(), other.quantity);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.creationDate)) {
        this.creationDate = data().deepCopy(fields()[7].schema(), other.creationDate);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.createdBy)) {
        this.createdBy = data().deepCopy(fields()[8].schema(), other.createdBy);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.lastModifiedDate)) {
        this.lastModifiedDate = data().deepCopy(fields()[9].schema(), other.lastModifiedDate);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.lastModifiedBy)) {
        this.lastModifiedBy = data().deepCopy(fields()[10].schema(), other.lastModifiedBy);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[11].schema(), other.timestamp);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.categoryIds)) {
        this.categoryIds = data().deepCopy(fields()[12].schema(), other.categoryIds);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.categories)) {
        this.categories = data().deepCopy(fields()[13].schema(), other.categories);
        fieldSetFlags()[13] = true;
      }
    }

    /**
      * Gets the value of the 'originalId' field.
      * @return The value.
      */
    public java.lang.String getOriginalId() {
      return originalId;
    }


    /**
      * Sets the value of the 'originalId' field.
      * @param value The value of 'originalId'.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder setOriginalId(java.lang.String value) {
      validate(fields()[0], value);
      this.originalId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'originalId' field has been set.
      * @return True if the 'originalId' field has been set, false otherwise.
      */
    public boolean hasOriginalId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'originalId' field.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder clearOriginalId() {
      originalId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'snapshotId' field.
      * @return The value.
      */
    public java.lang.String getSnapshotId() {
      return snapshotId;
    }


    /**
      * Sets the value of the 'snapshotId' field.
      * @param value The value of 'snapshotId'.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder setSnapshotId(java.lang.String value) {
      validate(fields()[1], value);
      this.snapshotId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'snapshotId' field has been set.
      * @return True if the 'snapshotId' field has been set, false otherwise.
      */
    public boolean hasSnapshotId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'snapshotId' field.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder clearSnapshotId() {
      snapshotId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventType' field.
      * @return The value.
      */
    public java.lang.String getEventType() {
      return eventType;
    }


    /**
      * Sets the value of the 'eventType' field.
      * @param value The value of 'eventType'.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder setEventType(java.lang.String value) {
      validate(fields()[2], value);
      this.eventType = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'eventType' field has been set.
      * @return True if the 'eventType' field has been set, false otherwise.
      */
    public boolean hasEventType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'eventType' field.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder clearEventType() {
      eventType = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder setName(java.lang.String value) {
      validate(fields()[3], value);
      this.name = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder clearName() {
      name = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.String getDescription() {
      return description;
    }


    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder setDescription(java.lang.String value) {
      validate(fields()[4], value);
      this.description = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder clearDescription() {
      description = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'price' field.
      * @return The value.
      */
    public double getPrice() {
      return price;
    }


    /**
      * Sets the value of the 'price' field.
      * @param value The value of 'price'.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder setPrice(double value) {
      validate(fields()[5], value);
      this.price = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'price' field has been set.
      * @return True if the 'price' field has been set, false otherwise.
      */
    public boolean hasPrice() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'price' field.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder clearPrice() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantity' field.
      * @return The value.
      */
    public int getQuantity() {
      return quantity;
    }


    /**
      * Sets the value of the 'quantity' field.
      * @param value The value of 'quantity'.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder setQuantity(int value) {
      validate(fields()[6], value);
      this.quantity = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'quantity' field has been set.
      * @return True if the 'quantity' field has been set, false otherwise.
      */
    public boolean hasQuantity() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'quantity' field.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder clearQuantity() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'creationDate' field.
      * @return The value.
      */
    public java.time.Instant getCreationDate() {
      return creationDate;
    }


    /**
      * Sets the value of the 'creationDate' field.
      * @param value The value of 'creationDate'.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder setCreationDate(java.time.Instant value) {
      validate(fields()[7], value);
      this.creationDate = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'creationDate' field has been set.
      * @return True if the 'creationDate' field has been set, false otherwise.
      */
    public boolean hasCreationDate() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'creationDate' field.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder clearCreationDate() {
      creationDate = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdBy' field.
      * @return The value.
      */
    public java.lang.String getCreatedBy() {
      return createdBy;
    }


    /**
      * Sets the value of the 'createdBy' field.
      * @param value The value of 'createdBy'.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder setCreatedBy(java.lang.String value) {
      validate(fields()[8], value);
      this.createdBy = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'createdBy' field has been set.
      * @return True if the 'createdBy' field has been set, false otherwise.
      */
    public boolean hasCreatedBy() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'createdBy' field.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder clearCreatedBy() {
      createdBy = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastModifiedDate' field.
      * @return The value.
      */
    public java.time.Instant getLastModifiedDate() {
      return lastModifiedDate;
    }


    /**
      * Sets the value of the 'lastModifiedDate' field.
      * @param value The value of 'lastModifiedDate'.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder setLastModifiedDate(java.time.Instant value) {
      validate(fields()[9], value);
      this.lastModifiedDate = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'lastModifiedDate' field has been set.
      * @return True if the 'lastModifiedDate' field has been set, false otherwise.
      */
    public boolean hasLastModifiedDate() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'lastModifiedDate' field.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder clearLastModifiedDate() {
      lastModifiedDate = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastModifiedBy' field.
      * @return The value.
      */
    public java.lang.String getLastModifiedBy() {
      return lastModifiedBy;
    }


    /**
      * Sets the value of the 'lastModifiedBy' field.
      * @param value The value of 'lastModifiedBy'.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder setLastModifiedBy(java.lang.String value) {
      validate(fields()[10], value);
      this.lastModifiedBy = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'lastModifiedBy' field has been set.
      * @return True if the 'lastModifiedBy' field has been set, false otherwise.
      */
    public boolean hasLastModifiedBy() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'lastModifiedBy' field.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder clearLastModifiedBy() {
      lastModifiedBy = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder setTimestamp(long value) {
      validate(fields()[11], value);
      this.timestamp = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder clearTimestamp() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'categoryIds' field.
      * @return The value.
      */
    public java.util.List<java.lang.String> getCategoryIds() {
      return categoryIds;
    }


    /**
      * Sets the value of the 'categoryIds' field.
      * @param value The value of 'categoryIds'.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder setCategoryIds(java.util.List<java.lang.String> value) {
      validate(fields()[12], value);
      this.categoryIds = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'categoryIds' field has been set.
      * @return True if the 'categoryIds' field has been set, false otherwise.
      */
    public boolean hasCategoryIds() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'categoryIds' field.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder clearCategoryIds() {
      categoryIds = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'categories' field.
      * @return The value.
      */
    public java.util.List<com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef> getCategories() {
      return categories;
    }


    /**
      * Sets the value of the 'categories' field.
      * @param value The value of 'categories'.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder setCategories(java.util.List<com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef> value) {
      validate(fields()[13], value);
      this.categories = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'categories' field has been set.
      * @return True if the 'categories' field has been set, false otherwise.
      */
    public boolean hasCategories() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'categories' field.
      * @return This builder.
      */
    public com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.ProductEvent.Builder clearCategories() {
      categories = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProductEvent build() {
      try {
        ProductEvent record = new ProductEvent();
        record.originalId = fieldSetFlags()[0] ? this.originalId : (java.lang.String) defaultValue(fields()[0]);
        record.snapshotId = fieldSetFlags()[1] ? this.snapshotId : (java.lang.String) defaultValue(fields()[1]);
        record.eventType = fieldSetFlags()[2] ? this.eventType : (java.lang.String) defaultValue(fields()[2]);
        record.name = fieldSetFlags()[3] ? this.name : (java.lang.String) defaultValue(fields()[3]);
        record.description = fieldSetFlags()[4] ? this.description : (java.lang.String) defaultValue(fields()[4]);
        record.price = fieldSetFlags()[5] ? this.price : (java.lang.Double) defaultValue(fields()[5]);
        record.quantity = fieldSetFlags()[6] ? this.quantity : (java.lang.Integer) defaultValue(fields()[6]);
        record.creationDate = fieldSetFlags()[7] ? this.creationDate : (java.time.Instant) defaultValue(fields()[7]);
        record.createdBy = fieldSetFlags()[8] ? this.createdBy : (java.lang.String) defaultValue(fields()[8]);
        record.lastModifiedDate = fieldSetFlags()[9] ? this.lastModifiedDate : (java.time.Instant) defaultValue(fields()[9]);
        record.lastModifiedBy = fieldSetFlags()[10] ? this.lastModifiedBy : (java.lang.String) defaultValue(fields()[10]);
        record.timestamp = fieldSetFlags()[11] ? this.timestamp : (java.lang.Long) defaultValue(fields()[11]);
        record.categoryIds = fieldSetFlags()[12] ? this.categoryIds : (java.util.List<java.lang.String>) defaultValue(fields()[12]);
        record.categories = fieldSetFlags()[13] ? this.categories : (java.util.List<com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events.CategoryRef>) defaultValue(fields()[13]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProductEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProductEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProductEvent>
    READER$ = (org.apache.avro.io.DatumReader<ProductEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










