# ----- Spring Config ------
spring:
  application:
    name: category-service
  # --- SQL Database (Postgres) ---
  datasource:
    url: jdbc:postgresql://localhost:5433/category-command-db
    username: adminPostgresCommandDB
    password: P@ssw0rd
    driver-class-name: org.postgresql.Driver

  # --- Jpa Config ---------
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # --- Mongo DB Query DB --------
  data:
    mongodb:
      uri: mongodb://adminMongoQueryDB:password123@localhost:27018/categoryQueryDB?authSource=admin
      host: localhost
      port: 27018
      database: categoryQueryDB
      username: adminMongoQueryDB
      password: password123

  # --- Redis Caching  --------
    redis:
      host: localhost
      port: 6381

  cache:
    type: redis

  #-------- RabbitMQ --------------
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: secret

  # --- Kafka Configuration (merged producer + consumer) ---
  kafka:
   bootstrap-servers: "127.0.0.1:9092"
  
   # Producer (from command service)
   producer:
     key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
     value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
     properties:
       schema:
         registry:
           url: "http://127.0.0.1:8081"
  
    # Consumer (from query service)
   consumer:
     group-id: "category-query-consumer-group"
     keyDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
     valueDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
     properties:
       schema:
         registry:
           url: "http://127.0.0.1:8081"
       specific:
         avro:
           reader: "true"

 ## --- Broker Topics ---
broker:
  topics:
    categories-topic: categories-topic


# ----- Server Configs -----
server:
  port: 7070
  servlet:
    context-path: /ecommerce/api/v1


# Swagger UI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

    
# ---- Zipkin and Tracing Configs ----    
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # 100% traces (adjust for production, e.g. 0.1)
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans # Zipkin server URL


# ----- Eureka Discovery Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# --- Logging ---
logging:
  level:
    org.springframework.kafka: DEBUG
    org.springframework.cache: TRACE
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.repository.query: DEBUG
    org.mongodb.driver.protocol.command: DEBUG
    org.mongodb.driver.connection: DEBUG
