# Spring Boot Application Configuration
spring:
  application:
    name: product-command-service
  datasource:
    url: jdbc:postgresql://localhost:5432/products-command-db
    username: admin-products-command-db
    password: P@ssw0rd@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8081
  servlet:
    context-path: /ecommerce/api/v1