{
  "type": "record",
  "name": "ProductEvent",
  "namespace": "com.youssef.gamal.ecommerce.microservice.product.infrastructure.kafka.events",
  "fields": [
    {
      "name": "originalId",
      "type": "string"
    },
    {
      "name": "snapshotId",
      "type": "string"
    },
    {
      "name": "eventType",
      "type": "string"
    },
    {
      "name": "name",
      "type": "string"
    },
    {
      "name": "description",
      "type": ["null", "string"],
      "default": null
    },
    {
      "name": "price",
      "type": "double"
    },
    {
      "name": "quantity",
      "type": "int"
    },
    {
      "name": "creationDate",
      "type": [
        "null",
        { "type": "long", "logicalType": "timestamp-millis" }
      ],
      "default": null
    },
    {
      "name": "createdBy",
      "type": ["null", "string"],
      "default": null
    },
    {
      "name": "lastModifiedDate",
      "type": [
        "null",
        { "type": "long", "logicalType": "timestamp-millis" }
      ],
      "default": null
    },
    {
      "name": "lastModifiedBy",
      "type": ["null", "string"],
      "default": null
    },
    {
      "name": "timestamp",
      "type": "long"
    },
    {
      "name": "categoryIds",
      "type": [
        "null",
        { "type": "array", "items": "string" }
      ],
      "default": null
    },
    {
      "name": "categories",
      "type": [
        "null",
        {
          "type": "array",
          "items": {
            "name": "CategoryRef",
            "type": "record",
            "fields": [
              { "name": "snapshotId", "type": "string" },
              { "name": "originalId", "type": "string" }
            ]
          }
        }
      ],
      "default": null
    }
  ]
}
