package com.youssef.gamal.ecommerce.microservice.category.query.entities;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@SuppressWarnings("serial")
@Document(collection = "categories")
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class CategoryView implements Serializable {

	@Id
	@Builder.Default
    private String  snapshotId = UUID.randomUUID().toString(); // generated by mongoDB for current snapshot of the category-view

    private String originalId; // snapshotId of the category in the command service

    private String name;

    private LocalDateTime creationDate;

    private String createdBy;

    private LocalDateTime lastModifiedDate;

    private String lastModifiedBy;

    private String eventType;
}
