services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=productQueryDb'
      - 'MONGO_INITDB_ROOT_PASSWORD=Password123'
      - 'MONGO_INITDB_ROOT_USERNAME=adminProductsQueryDB'
    ports:
      - '27017:27017'
